# Solution voor de Invuloefening 

Vul de volgende woorden op de juiste plaats in: `Class`, `instance`, `method`, `operation`, `object`, `Field`. Let op: een woord kan meerdere malen in de tekst voorkomen.

Een programmeur moet van zijn baas binnen een game de `class` "Karakter" programmeren. "Karakter" is reeds gespecificeerd door middel van een kaartje waar alle verantwoordelijkheden op staan. Ook krijgt hij een klassendiagram met een duidelijk overzicht van de `operations` (waaronder MoveForward en ValDoodNeer) 
en `attributes` (zoals bijvoorbeeld AantalLevens, HaarKleur en AantalWapens).

De programmeur neemt het kaartje en opent het bestaande project in Visual Studio. Daar gaat hij dan de nieuwe `class` in programmeren. Als eerste programmeert hij `Fields` voor AantalLevens en HaarKleur en vervolgens mapt hij de `operaties` MoveForward en ValDoorNeer naar C#-methoden.

Als hij de `class` helemaal heeft geprogrammeerd gaat hij deze testen door er met de new-operator een `object` (of: `instance`) van aan te maken. Hij roept de `method` MoveForward aan om te testen of het karakter de goede kant op beweegt.
Ja, het werkt! Hij maakt nog een instantie van Karakter aan om te testen of het programma dan nog steeds werkt. Ja! 

Met een voldaan gevoel gaat de programmeur aan het eind van de dag naar huis.


