

# Wat is een Class?

Er wordt vaak gezegd dat een `Class` een soort van *blauwdruk* is: een *beschrijving* 	hoe iets er uit moet gaan zien en wat dat `ding` (inderdaad: `object`) kan gaan doen. Een 'class' definieert een `type`. 

Van een boot maak je eerst een `design`, een `ontwerp`: Wat voor soort hout heb je nodig? Waar liggen de verbindingen? Wat voor een motor komt er in te liggen? Et cetera. 

Deze tekening, de blauwdruk, kan niet varen. Je kunt er niet op dobberen. Pas wanneer de boot wordt gemaakt kun je er iets mee gaan doen. Je kunt er zelfs meerdere boten van maken! Zo is het met classes ook. Een **class** is dus een blauwdruk voor een **ding**, een **object**. Je kunt er pas mee aan de slag op het moment dat je de blauwdruk ***instantieert***: een **object** van dat ***type*** maakt.

Een andere vergelijking is dat je een `class` kunt vergelijken met een **lopende band**: Van een lopende band kunnen meerdere dingen (`objecten`) van een bepaald `type` afrollen: Elke keer dat ik `new` roep tegen de class komt er een object van dat type van de lopende band afrollen. Hoe de lopende band is 'geprogrammeerd' bepaalt wat een object van dat type uiteindelijk kan.

