# Workshops (en inspi voor meer...)
Informatie voor workshops en inspiratie voor meer.

## Weekschema Workshops
Een mogelijk weekschema voor FHICT. Het is de bedoeling dat softwaredocenten tijdens de Verdieping binnen hun cluster overleggen welke workshops wanneer door wie (samen?) gedaan worden.

## Design Challenge (tussen oriëntatie en verdieping)

+ git-workshop (versiebeheer)

## Verdiepingsperiode

### 1e week Verdieping

+ [CRC workshop](../objects/crc/crc)
+ Overview inhoud van de verdieping
+ demo: introductie class / object / ctor

### 2e week Verdieping

+ demo: property & override ToString() (met herhaling class / object / ctor), bijvoorbeeld [Crossing](Crossing)
+ Methods met (eigen) classes als parameter en returntype.
+ van class diagram naar code.

### 3e week Verdieping

+ 'as' / (Casting?) / ('is'?)
+ multipliciteit: class diagram vs code
+ [Compiler Error Quiz](errorquiz)
+ [Game of Life](conway)
+ demo: een wat groter voorbeeld met class/object/ctor/propg etc... bijvoorbeeld [Virusinator](Virusinator)
+ [git-workshop](git)

### 4e week Verdieping

+ unit test (game)
+ Files lezen/schrijven
+ Database select/insert/update  (Jeroen maakt deze)
+ [Web API maken](webApi01_CS/MaakJeEigenApi.pdf)
+ demo: voorproefje S2: interfaces & inheritance
        (studenten hebben hier vlak voor de deadline wellicht geen interesse in...)
        voor de definitieve profielkeuze
+ [GUI vs Domain](GuiVsDomain)

### Laatste weken Verdieping

Hier laten we de studenten hard werken aan het product vanwege de deadlines, eventueel workshops op aanvraag of ad hoc.


+ [99 bottloes of beer on the wall](99bottlesOfBeer)

+ [Vergelijking OOP in andere talen?](OOP_languages/)
  1. Python: Infra gebruikt python in semester 2.
  2. Javascript: GUI tegenwoordig vaak een web-GUI, dan is javascript nooit ver weg.
  3. PHP: Veel studenten komen sowieso in aanraking met PHP.
  4. ... nog andere talen?



## Meer inspiratie...

Losse ideeën en onaffe workshops in. Doe er uw voordeel mee!

+ [Web API maken](webApi01_CS/MaakJeEigenApi.pdf)
+ [Sinterklaas-demo-inspiratie](inspi/SintEnPiet.zip)
+ [galgje-ish (demo)](galgje-ish/galgjeish)
