# String manipulatie: Dr. Bobby

Dr. Bobby is een computerpsychiater. Jij gaat Dr. Bobby programmeren door een programma te schrijven dat voldoet aan de volgende requirements:
      
De gebruiker kan een vraag stellen aan het systeem door deze in te typen in een textbox en op een knop te klikken. Na het klikken op de knop verschijnt het antwoord.

1. Als de vraag begint met het woord _waarom_ dan antwoord Dr. Bobby met "Waarom denkt u zelf?". 
2. Als de vraag begint met het woord _wie_ dan antwoord Dr. Bobby met "Wie denkt u zelf, <rest>" waarbij <rest> gelijk is aan de door de gebruiker ingevulde tekst minus _wie_. Voorbeeld: De gebruiker typt "Wie is Sinterklaas?" Dr. Bobby: Wie denkt u zelf, is Sinterklaas?" 
3. Als de vraag begint met het woord _wat_ dan antwoord Dr. Bobby met "Wat denkt u, <rest>" waarbij <rest> gelijk is aan de door de gebruiker ingevulde tekst minus _wat_. Voorbeeld: De gebruiker typt "Wat is het doel van dit gesprek?" Dr. Bobby: Wat denkt u zelf, is het doel van dit gesprek?" 
4. In overige gevallen antwoord Dr. Boddy "Waarom wilt u dat weten, denkt u?" 
