# Wat kan ik als ik de basis beheers?

## Toelichting Oriënterend niveau

Je past de volgende programmeer-concepten toe en hebt voorbeelden waaruit blijkt dat je de volgende concepten beheerst:

DIT IS GEEN AFVINK-LIJST!

+ Variable
+ Conditional statement
+ Loop
+ Methods
+ Parameters bij Methods
+ Returnvalues bij Methods
+ List
+ Array
+ Enum
+ type int, string, double, bool

Ook heb je de volgende vaardigheden laten zien en/of er aan gewerkt:
+ Leesbaarheid / Onderhoudbaarheid
+ Algoritmiek
+ Feedback gevraagd van docent, genoteerd in feedpulse en laat zien wat je met deze feedback gedaan hebt.
+ Professioneel gecommuniceerd. Met name ben ik op tijd, meld ik me af bij docent als ik er een keer niet of te laat ben.  

Een "soort" checklist (niet-compleet) die kan helpen:
+ Om concepten onder de knie te krijgen en ermee te oefenen heb je een aantal 'trainingen' gedaan.
+ In de 'wedstrijd' laat je zien wat je kunt. In een wedstrijd-app, een voor de 'wedstrijd' gemaakte app(licatie), laat je zien dat je weet hoe meerdere concepten binnen een onderhoudbare app worden gebruikt.
+ Om jezelf en een docent te overtuigen dat je methods kunt maken heb je minstens 15 methods gemaakt, waarvan minstens 5 binnen 1 wedstrijd-solution/project.
+ Je hebt minstens 5 methods gemaakt die (tenminste) 1 parameter hebben.
+ Minstens 5 methods met een returnvalue.
