# Bloeddruk meten

## Context

Je bent als software engineer ingehuurd om voor een ziekenhuis een app te programmeren die gebruikt wordt om de bloeddruk van mensen te checken.

Analyse/vooronderzoek heeft deze informatie opgeleverd: [https://nl.wikipedia.org/wiki/Bloeddruk](https://nl.wikipedia.org/wiki/Bloeddruk)

## Start

## Opdracht 0: Must haves

1.  Gebruiker moet de leeftijd van de patiënt kunnen invullen.
2.  Gebruiker moet met een radiobutton aan kunnen geven of het een man of vrouw is. Dit moet met radio buttons worden geprogrammeerd.
3.  Gebruiker moet de bloeddruk in kunnen vullen. Deze bestaat uit twee verschillende invulvelden: bovendruk en onderdruk.
4.  Gebruiker moet naam van de patiënt in kunnen vullen.
5.  Het systeem moet de volgende informatie op een overzichtelijke wijze aan de gebruiker laten zien:

-   Of de patiënt een Hoge, Lage, Optimale of Normale bloeddruk heeft. Tip: hierbij heb je de formule nodig die de gemiddelde bloeddruk Pgemiddeld uitrekent (zie Wikipediapagina).
-   Indien de patiënt een man is moet het scherm (achtergrondkleur, form) blauw worden en anders roze.

7.  Er moet op een logische wijze van methoden gebruikt gemaakt worden, minimaal 1 functionele methode.
8.  Als de patiënt een man is van boven de 65 of een vrouw van boven de 67 dan moet de melding "Patiënt heeft extra aandacht nodig" verschijnen indien de bloeddruk Hoog is.
9.  Er staat geen code in de eventhandlers van buttons en dergelijk behalve aanroepen naar methoden.
